preset: none

enabled:
# File
- encoding
- full_opening_tag
- no_closing_tag
# Array
- no_whitespace_before_comma_in_array
- short_array_syntax
- trim_array_spaces
# Blank line
- linebreak_after_opening_tag
- blank_line_after_namespace
- no_blank_lines_after_class_opening
- no_blank_lines_after_return
- no_blank_lines_after_throw
# Other
- align_comments
- class_definition
- combine_consecutive_unsets
- concat_with_spaces
- const_visibility_required
- dir_constant
- print_to_echo
- hash_to_slash_comment
- is_null
- lowercase_cast
- method_separation
- method_visibility_required
- native_function_casing
- no_empty_comment
- no_php4_constructor
- no_spaces_after_function_name
- no_useless_else
- no_useless_return
- non_printable_character
- property_visibility_required
- protected_to_private
- self_accessor
- simplified_null_return
- single_quote
- standardize_not_equals

disabled:
